### PR TITLE
Consul DNS resolving

### PR DESCRIPTION
**Pull request by jakubno**
Allow to use consul for DNS, we need this for specifying a service on an exact node.

### CODE REVIEW

**Comment by jakubno** [comment]
It's possible this won't be needed

**Comment by ValentaTomas** [comment]
> Not needed

Why, what are we using now?

**Comment by jakubno** [comment]
We use nomad client library to get all available nodes and it also gives us the IP address of the node directly, so there's no need for extra consul DNS resolving

**Comment by jakubno** [comment]
Actually, we probably need this 😅  to reference services from all nodes, because they probably won't be accessible on localhost

**Pull request closed without merging**
